# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='fav_keywords',
            field=models.ManyToManyField(blank=True, to='contests.FavoriteKeyword'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='favorited_list',
            field=models.ManyToManyField(blank=True, related_name='favorited_list', to='contests.Tweet'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='follow_keywords',
            field=models.ManyToManyField(blank=True, to='contests.FollowKeyword'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='ignore_list',
            field=models.ManyToManyField(blank=True, related_name='ignore_list', to='contests.TwitterUser'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='retweet_follow_list',
            field=models.ManyToManyField(blank=True, related_name='retweet_follow_list', to='contests.Tweet'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='retweet_list',
            field=models.ManyToManyField(blank=True, related_name='retweet_list', to='contests.Tweet'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='search_queries',
            field=models.ManyToManyField(blank=True, to='contests.SearchQuery'),
        ),
    ]
