# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20170215_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='id_str',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
