# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_twitteruser_id_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='id_str',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='id_str',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
