# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20170215_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Bot'),
        ),
    ]
