# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_tweet_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='post_list',
            field=models.ManyToManyField(blank=True, related_name='post_queue', to='contests.Tweet'),
        ),
    ]
