# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_bot_post_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='twitter_id',
        ),
    ]
