# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_auto_20170215_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
