# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_log_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Retweet'), ('1', 'Favorite'), ('2', 'Follow'), ('3', 'Scan'), ('x', 'Error')], default='0', max_length=1, null=True),
        ),
    ]
