# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_log_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='status',
            new_name='type',
        ),
    ]
