# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_auto_20170215_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='min_ratelimit_talk',
            field=models.IntegerField(default=40, help_text='minimum rate limit for random talking'),
        ),
        migrations.AddField(
            model_name='bot',
            name='talk_update_time',
            field=models.IntegerField(default=1000, help_text='how often to puke up text'),
        ),
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'Retweet'), ('1', 'Favorite'), ('2', 'Follow'), ('3', 'Scan'), ('4', 'Tweet'), ('x', 'Error')], default='0', max_length=1, null=True),
        ),
    ]
