# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_auto_20170215_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gibberish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
    ]
