# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0013_auto_20170215_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255)),
                ('display', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='tweet_generator',
            field=models.ManyToManyField(blank=True, to='contests.TweetGenerator'),
        ),
    ]
