# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0014_auto_20170215_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('tweet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contests.Tweet')),
                ('responded', models.BooleanField(default=False)),
            ],
            bases=('contests.tweet',),
        ),
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'Retweet'), ('1', 'Favorite'), ('2', 'Follow'), ('3', 'Scan'), ('4', 'Tweet'), ('5', 'Get Mentions'), ('x', 'Error')], default='0', max_length=1, null=True),
        ),
    ]
