# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0015_auto_20170215_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='screen_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'Retweet'), ('1', 'Favorite'), ('2', 'Follow'), ('3', 'Scan'), ('4', 'Tweet'), ('x', 'Error')], default='0', max_length=1, null=True),
        ),
    ]
