# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0016_auto_20170215_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='reply',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
