# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0017_tweet_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mention',
            name='tweet_ptr',
        ),
        migrations.AddField(
            model_name='tweet',
            name='twitter_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='twitter_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Mention',
        ),
    ]
