# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0019_auto_20170215_2042'),
        ('contests', '0013_gibberish'),
    ]

    operations = [
    ]
